version: '3.9'
services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
    mosquitto:
        image: olimungo/mosquitto
        container_name: mosquitto
        build: ./mosquitto
        ports:
            - 1883:1883
        expose:
            - 1883
    websockets:
        image: olimungo/nestor-websockets
        container_name: websockets
        build: ./websockets
        volumes:
            - ./websockets/scripts:/usr/src/app/scripts
        ports:
            - 9000:9000
        environment:
            - NODE_ENV=development
            - PORT=9000
            - REDIS_URL=redis://redis
            - CORS_ORIGIN=http://localhost:3000
    mqtt:
        image: olimungo/nestor-mqtt
        container_name: mqtt
        build: ./mqtt
        volumes:
            - ./mqtt/scripts:/usr/src/app/scripts
        ports:
            - 9001:9001
        environment:
            - NODE_ENV=development
            - PORT=9001
            - REDIS_URL=redis://redis
            # - MOSQUITTO_URL=mqtt://nestor.local
            - MOSQUITTO_URL=mqtt://mosquitto
    # nestor:
    #     image: olimungo/nestor
    #     container_name: nestor
    #     build: ./nestor
    #     ports:
    #         - 80:80
    #     environment:
    #         - NODE_ENV=development
