version: '3.9'
services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
    mosquitto:
        image: olimungo/mosquitto
        container_name: mosquitto
        build: ./mosquitto
        ports:
            - 1883:1883
        expose:
            - 1883
    # mqtt:
    #     image: olimungo/nestor-mqtt
    #     container_name: mqtt
    #     build: ./mqtt
    #     volumes:
    #         - ./:/var/www/app
    #     ports:
    #         - 3000:3000
    #     environment:
    #         - NODE_ENV=development
    #         - PORT=3000
    #         - REDIS_URL=redis://redis
    #         - MOSQUITTO_URL=mqtt://nestor.local
    #         # - MOSQUITTO_URL=mqtt://mosquitto
    # websockets:
    #     image: olimungo/nestor-websockets
    #     container_name: websockets
    #     build: ./websockets
    #     volumes:
    #         - ./:/var/www/app
    #     ports:
    #         - 3001:3001
    #     environment:
    #         - NODE_ENV=development
    #         - PORT=3001
    #         - REDIS_URL=redis://redis
