version: '3'
services:
    node:
        image: 'node:10'
        user: 'node'
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        expose:
            - '8081'
        ports:
            - '8081:8081'
        command: 'npm start'
