version: '3.9'
services:
    redis:
        image: arm32v7/redis
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
    mosquitto:
        image: olimungo/mosquitto:0.1
        container_name: mosquitto
        ports:
            - 1883:1883
        expose:
            - 1883
    websockets:
        image: olimungo/nestor-websockets:0.4
        container_name: websockets
        ports:
            - 9000:9000
        environment:
            - NODE_ENV=production
            - PORT=9000
            - REDIS_URL=redis://redis
            - CORS_ORIGIN=http://nestor.local,http://192.168.0.235
    mqtt:
        image: olimungo/nestor-mqtt:0.3
        container_name: mqtt
        ports:
            - 9001:9001
        environment:
            - NODE_ENV=production
            - PORT=9001
            - REDIS_URL=redis://redis
            - MOSQUITTO_URL=mqtt://mosquitto
    nestor:
        image: olimungo/nestor:0.105
        container_name: nestor
        ports:
            - 80:80
        environment:
            - NODE_ENV=production
